# Generated by Django 5.2.2 on 2025-06-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('long', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='race date')),
                ('name', models.CharField(max_length=250)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('humidity', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precip_prob', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('showers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snowfall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_gusts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.location')),
            ],
        ),
    ]
