# Generated by Django 5.2.2 on 2025-06-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_weather_humidity_alter_weather_precip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
